src/Entity/Location.php
<?php

namespace App\Entity;

use App\Repository\LocationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LocationRepository::class)]
class Location
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_location = null;

    #[ORM\Column]
    private ?int $nb_jr_location = null;

    #[ORM\Column]
    private ?int $prix_location = null;

    #[ORM\ManyToMany(targetEntity: Modele::class, inversedBy: 'locations')]
    private Collection $modele;

    public function __construct()
    {
        $this->modele = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateLocation(): ?\DateTimeInterface
    {
        return $this->date_location;
    }

    public function setDateLocation(\DateTimeInterface $date_location): static
    {
        $this->date_location = $date_location;

        return $this;
    }

    public function getNbJrLocation(): ?int
    {
        return $this->nb_jr_location;
    }

    public function setNbJrLocation(int $nb_jr_location): static
    {
        $this->nb_jr_location = $nb_jr_location;

        return $this;
    }

    public function getPrixLocation(): ?int
    {
        return $this->prix_location;
    }

    public function setPrixLocation(int $prix_location): static
    {
        $this->prix_location = $prix_location;

        return $this;
    }

    /**
     * @return Collection<int, modele>
     */
    public function getModele(): Collection
    {
        return $this->modele;
    }

    public function addModele(Modele $modele): static
    {
        if (!$this->modele->contains($modele)) {
            $this->modele->add($modele);
        }

        return $this;
    }

    public function removeModele(Modele $modele): static
    {
        $this->modele->removeElement($modele);

        return $this;
    }
}

src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?int $nb_km = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createAt = null;

    #[ORM\OneToMany(mappedBy: 'voiture', targetEntity: Loueur::class)]
    private Collection $loueurs;

    public function __construct()
    {
        $this->loueurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getNbKm(): ?int
    {
        return $this->nb_km;
    }

    public function setNbKm(int $nb_km): static
    {
        $this->nb_km = $nb_km;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeImmutable $createAt): static
    {
        $this->createAt = $createAt;

        return $this;
    }

    /**
     * @return Collection<int, Loueur>
     */
    public function getLoueurs(): Collection
    {
        return $this->loueurs;
    }

    public function addLoueur(Loueur $loueur): static
    {
        if (!$this->loueurs->contains($loueur)) {
            $this->loueurs->add($loueur);
            $loueur->setVoiture($this);
        }

        return $this;
    }

    public function removeLoueur(Loueur $loueur): static
    {
        if ($this->loueurs->removeElement($loueur)) {
            // set the owning side to null (unless already changed)
            if ($loueur->getVoiture() === $this) {
                $loueur->setVoiture(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\VoitureRepository;
use App\Entity\Voiture;
use App\Repository\LocationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    // Architecture MVC
    // 1- Envoyer une requete http en saisisant les données à partir de l'URL d'un navigateur 
    // 2- Récupérer la requete http par le 'controleur' (controller) 
    // 3- si besoin le controleur appelle le 'model' et envoi la requete vers le model afin d'interagir avec la bdd
    // 4- Le model envoie la reponse au controleur
    // 5-Controleur récupère la réponse du model et il l'envoie vers la 'vue'(view)


    // #[Route('/home', name: 'app_home')] => vu navigateur http://127.0.0.1:8000/home
    //  '/home' est le nom du chemin qui peut etre modifie 
    // exemple #[Route('/moi', name: 'app_home')] => vu navigateur http://127.0.0.1:8000/moi
    // les routes doivent etre unique

    //name: 'app_home' est le nom de la route pour un lien => a href="{{ path('app_moi')}}"

    #[Route('/home', name: 'app_home')]
    
    public function index(VoitureRepository $voitureRepository): Response
    {
        $voitures = $voitureRepository->findAll();

        return $this->render('home/home.html.twig', [
            
            'voitures'=>$voitures,
        ]);
    }

    #[Route('/show_voit/{id}', name: 'show_voit')]
    
    public function show(VoitureRepository $voitureRepository,$id): Response
    {
        $voiture = $voitureRepository->find($id);

        return $this->render('home/show_voit.html.twig', [
            'voiture'=>$voiture,
        ]);
    }

    #[Route('/locationList', name:'list_location')]
    
    public function listLocation(LocationRepository $locationRepository): Response
    {
        $locations = $locationRepository->findListLocationActif();

        return $this->render('home/list_location.html.twig', [
            'locations'=>$locations,
        ]);
    }
}

templates/home/home.html.twig
{% extends 'base.html.twig' %} 

{% block title %}

{% endblock %} 

{% block body %}

<div class="example-wrapper">
  <h1>Liste</h1>

  <div class="row row-cols-1 row-cols-md-2 g-4">
    
    {% for voiture in voitures %}
    
      <div class="col">
        <div class="card bg-transparent border-warning border-2">
            <img src="{{ voiture.image }}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title link-light">{{ voiture.nom | upper }}</h5>

              <a href="{{path('show_voit',{'id': voiture.id})}}" class="btn btn-secondary my-2 my-sm-0  mt-2 fw-bolder list-group">En Savoir plus</a>

              <p class="card-text link-warning h6 mt-2 fw-semibold">{{ voiture.createAt|date('d.m.Y H:i:s')}}</p>
              <p class="nb_km link-light fw-semibold">{{ voiture.nbKm | raw }} kms</p>

            </div>
          </div>
        </div>
    {% endfor %}
  </div>

</div>
{% endblock %}


{# code formateur
<div class="row">
  {% for article in articles %}
  <div class="card col-md-4" style="width: 18rem;">
      <p class="date">{{ article.createdAt | date("d/m/y")}}</p>
      <img src="{{article.image}}" class="card-img-top" alt="{{ article.title }}">
      <div class="card-body">
        <h5 class="card-title"> {{article.title }}</h5>
        <a href="#" class="btn btn-primary">En Savoir plus</a>
      </div>
    </div>
  {% endfor %}
</div> #}

templates/home/list_location.html.twig
{% extends 'base.html.twig' %} 

{% block title %}

{% endblock %} 

{% block body %}
<div class="row m-5">
<h1>Liste des véhicules loués</h1>

    {% for location in locations %}
        <div class="card col-md-4 link-warning bg-primary border border-danger-subtle border-2" style="width: 18rem;">
            <p class="date mx-lg-auto fw-bolder">{{ location.dateLocation | date("d/m/y")}}</p>
            <p class="nb_jr_location link-light fw-semibold">Nombre de jour de location :{{ location.nbJrLocation | raw }} </p>
            <div class="card-body">
                <p class="prix_location link-dark fw-semibold">Prix de la location : {{ location.prixLocation | raw }} €</p
            </div>
        </div>
</div>
    {% endfor %}

{% endblock %}

templates/home/show_voit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Détails Article {% endblock %}

{% block body %}
<div class="example-wrapper">
    <h1> Véhicules du parc </h1>
</div>
<div class="container">
    <h5 class="nom link-warning"> {{voiture.nom }}</h5>
    <div class="img-fluid border border-2 border-secondary figure ">
        <img src="{{voiture.image}}" alt="{{ voiture.nom }}">
    </div>
    <div class="content">
        <p class="date link-warning mt-3 fw-semibold">Ecrit le {{ voiture.createAt | date("d.m.y")  }} à {{ voiture.createAt | date("H:m") }}</p>
        <p class="nb_km link-light fw-semibold">kilomètrages : {{ voiture.nbKm | raw }} kms</p>
    </div>  
</div>

{% endblock %}